# Generated by Django 4.2.5 on 2023-10-09 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitora_consumo_agua', '0005_alter_consumoagua_consumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensores_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.AddField(
            model_name='consumoagua',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_sensores', to='monitora_consumo_agua.sensor'),
        ),
    ]
