# Generated by Django 4.2.5 on 2023-10-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitora_consumo_agua', '0006_sensor_consumoagua_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='codigo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
