# Generated by Django 4.2.5 on 2023-10-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitora_consumo_agua', '0007_alter_sensor_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
